### ISSUE TITLE
Duplicated "state" column in data table

### ISSUE THREAD

**Issue by strepon** [RonakRah/shiny_app#5] opened 2023-01-05 18:49 UTC
It is not needed to have state names in the data table as both column and row labels - the sortable column is enough.

**Comment by RonakRah** [comment] 2023-01-30 18:53
Dear Mr. Stanislav Horáček, the row names are removed.

**Comment by strepon** [comment] 2023-01-31 20:32
As there is no pull request for this, I will comment it here:

I would prefer another solution as row names could be used elsewhere. Also, now numbers are shown in the data table which is not needed.

The solution could be to pass an argument controlling row names to the function rendering the table - I guess the used data table supports it as it is a common request.

**Comment by RonakRah** [comment] 2023-04-04 15:35
the issue is fixed in https://github.com/RonakRah/shiny_app/pull/9 pull request. would you please review it @strepon

**Comment by RonakRah** [comment] 2023-04-04 21:51
#9 merged

**Closed by RonakRah** 2023-04-04 21:51 UTC
