### ISSUE TITLE
Type of arrest control

### ISSUE THREAD

**Issue by strepon** [RonakRah/shiny_app#6] opened 2023-01-05 18:50 UTC
It is a bit confusing that the "type of arrest" select box is above the map - I would expect it in the left panel as it is for charts.

There is also a possibility to use a common select box for both charts and map...

**Comment by RonakRah** [comment] 2023-01-30 18:54
Dear Mr. Stanislav Horáček, the select box is moved to the left panel.

**Comment by RonakRah** [comment] 2023-04-04 17:58
the issue is fixed in the arrest-controle#6 pull request. would you please review it @strepon

**Comment by RonakRah** [comment] 2023-04-04 18:03
the issue is fixed in the #8 pull request. would you please review it @strepon

**Comment by RonakRah** [comment] 2023-04-04 21:50
#8 merged

**Comment by RonakRah** [comment] 2023-04-04 21:51
#8 merged

**Closed by RonakRah** 2023-04-04 21:51 UTC
